//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftLocalizer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftLocalizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AI Translation Settings.
        /// </summary>
        public static string AiTranslationSettingsHeader {
            get {
                return ResourceManager.GetString("AiTranslationSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на API Key:.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto install.
        /// </summary>
        public static string AutoInstall {
            get {
                return ResourceManager.GetString("AutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch Size:.
        /// </summary>
        public static string BatchSize {
            get {
                return ResourceManager.GetString("BatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch size is how many lines are sent per request. 
        ///
        ///Larger is faster, but higher error risk..
        /// </summary>
        public static string BatchSizeTooltip {
            get {
                return ResourceManager.GetString("BatchSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Better Questing folder not found..
        /// </summary>
        public static string BetterQuestingFilesMissingMessage {
            get {
                return ResourceManager.GetString("BetterQuestingFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click selection mode.
        /// </summary>
        public static string ClickSelectionMode {
            get {
                return ResourceManager.GetString("ClickSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collecting dependencies.
        /// </summary>
        public static string CollectingRequirements {
            get {
                return ResourceManager.GetString("CollectingRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string ConfirmationNo {
            get {
                return ResourceManager.GetString("ConfirmationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string ConfirmationYes {
            get {
                return ResourceManager.GetString("ConfirmationYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For selecting a provider and model, start the translation in GPT4Free mode..
        /// </summary>
        public static string ConnectionGPT4FreeError {
            get {
                return ResourceManager.GetString("ConnectionGPT4FreeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Console.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Console text.
        /// </summary>
        public static string ConsoleText {
            get {
                return ResourceManager.GetString("ConsoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search in table....
        /// </summary>
        public static string DataGridSearchPlaceholder {
            get {
                return ResourceManager.GetString("DataGridSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeepSeek API Key:.
        /// </summary>
        public static string DeepSeekApiKey {
            get {
                return ResourceManager.GetString("DeepSeekApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeepSeek API key is not configured.
        ///
        ///Please create an API key on platform.deepseek.com and set it in settings..
        /// </summary>
        public static string DeepSeekApiKeyMissingMessage {
            get {
                return ResourceManager.GetString("DeepSeekApiKeyMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The DeepSeek API key can be obtained at platform.deepseek.com..
        /// </summary>
        public static string DeepSeekApiKeyTooltip {
            get {
                return ResourceManager.GetString("DeepSeekApiKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string DialogServiceErrorTitle {
            get {
                return ResourceManager.GetString("DialogServiceErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string DialogServiceInformationTitle {
            get {
                return ResourceManager.GetString("DialogServiceInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string DialogServiceSuccessTitle {
            get {
                return ResourceManager.GetString("DialogServiceSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directory path:.
        /// </summary>
        public static string DirectoryPath {
            get {
                return ResourceManager.GetString("DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download complete, starting installation....
        /// </summary>
        public static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading Gpt4Free.
        /// </summary>
        public static string DownloadingGpt4Free {
            get {
                return ResourceManager.GetString("DownloadingGpt4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drag selection mode.
        /// </summary>
        public static string DragSelectionMode {
            get {
                return ResourceManager.GetString("DragSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error detected.
        /// </summary>
        public static string ErrorDetected {
            get {
                return ResourceManager.GetString("ErrorDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load models.
        /// </summary>
        public static string FailedToLoadModelsMessage {
            get {
                return ResourceManager.GetString("FailedToLoadModelsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load providers.
        /// </summary>
        public static string FailedToLoadProvidersMessage {
            get {
                return ResourceManager.GetString("FailedToLoadProvidersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to reset settings.
        /// </summary>
        public static string FailedToResetSettingsMessage {
            get {
                return ResourceManager.GetString("FailedToResetSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File....
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finalizing downloading.
        /// </summary>
        public static string FinalizingDownloading {
            get {
                return ResourceManager.GetString("FinalizingDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FTB Quests folder not found..
        /// </summary>
        public static string FTBQuestsFilesMissingMessage {
            get {
                return ResourceManager.GetString("FTBQuestsFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The GPT4Free API key can be obtained at g4f.dev. It increases service limits:
        ///
        ///- up to 10 requests per minute (instead of 5);
        ///- up to 100 requests per hour (instead of 50)..
        /// </summary>
        public static string Gpt4FreeApiKeyTooltip {
            get {
                return ResourceManager.GetString("Gpt4FreeApiKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation may take a few minutes. Do not close the program until installation is complete!.
        /// </summary>
        public static string Gpt4FreeInstallationWarning {
            get {
                return ResourceManager.GetString("Gpt4FreeInstallationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For the best translation quality, it is recommended to use the paid DeepSeek mode.
        ///
        ///DeepSeek handles context more accurately, has no limits, and makes fewer mistakes.
        ///
        ///Continue with GPT4Free?.
        /// </summary>
        public static string Gpt4FreeWarningMessage {
            get {
                return ResourceManager.GetString("Gpt4FreeWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation completed successfully!.
        /// </summary>
        public static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing....
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing Gpt4Free.
        /// </summary>
        public static string InstallingGpt4Free {
            get {
                return ResourceManager.GetString("InstallingGpt4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing packages....
        /// </summary>
        public static string InstallingPackages {
            get {
                return ResourceManager.GetString("InstallingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The prompt can contain at most one placeholder {0}, or none at all. If there are no placeholders, the target language must be manually specified..
        /// </summary>
        public static string InvalidPromptMessage {
            get {
                return ResourceManager.GetString("InvalidPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launching Gpt4Free....
        /// </summary>
        public static string LaunchingGpt4Free {
            get {
                return ResourceManager.GetString("LaunchingGpt4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading providers....
        /// </summary>
        public static string LoadingProvidersStatus {
            get {
                return ResourceManager.GetString("LoadingProvidersStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        public static string LoadingWindowTitle {
            get {
                return ResourceManager.GetString("LoadingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main Settings.
        /// </summary>
        public static string MainSettingsHeader {
            get {
                return ResourceManager.GetString("MainSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model:.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A model is a specific version of an AI (e.g., GPT-4, DeepSeek-V3, Claude-3).
        ///
        ///Models differ in:
        ///- response and translation quality,
        ///- speed,
        ///- supported languages.
        ///
        ///Recommended models: DeepSeek or Gemma..
        /// </summary>
        public static string ModelTooltip {
            get {
                return ResourceManager.GetString("ModelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mods folder not found..
        /// </summary>
        public static string ModsFilesMissingMessage {
            get {
                return ResourceManager.GetString("ModsFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mods translation.
        /// </summary>
        public static string ModsModeTitle {
            get {
                return ResourceManager.GetString("ModsModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No checked files to save!.
        /// </summary>
        public static string NoCheckedFilesSavingMessage {
            get {
                return ResourceManager.GetString("NoCheckedFilesSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No checked files to translate!.
        /// </summary>
        public static string NoCheckedFilesTranslatingMessage {
            get {
                return ResourceManager.GetString("NoCheckedFilesTranslatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No models were returned for the selected provider..
        /// </summary>
        public static string NoModelsReturnedMessage {
            get {
                return ResourceManager.GetString("NoModelsReturnedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No providers were returned by the API..
        /// </summary>
        public static string NoProvidersReturnedMessage {
            get {
                return ResourceManager.GetString("NoProvidersReturnedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not installed.
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not selected.
        /// </summary>
        public static string NotSelectedModeTitle {
            get {
                return ResourceManager.GetString("NotSelectedModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File translation.
        /// </summary>
        public static string OneFileModeTitle {
            get {
                return ResourceManager.GetString("OneFileModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open directory.
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in explorer.
        /// </summary>
        public static string OpenFileInExplorer {
            get {
                return ResourceManager.GetString("OpenFileInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open resource pack.
        /// </summary>
        public static string OpenResourcePack {
            get {
                return ResourceManager.GetString("OpenResourcePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Original text.
        /// </summary>
        public static string OriginalText {
            get {
                return ResourceManager.GetString("OriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing....
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tool for translating Minecraft mods using GPT4Free..
        /// </summary>
        public static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program language:.
        /// </summary>
        public static string ProgramLanguage {
            get {
                return ResourceManager.GetString("ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt.
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Provider:.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A provider is the service through which requests are sent to the AI (e.g., OpenAI, DeepSeek, Anthropic, etc.).
        ///
        ///The selected provider affects:
        ///- model availability,
        ///- stability,
        ///- response speed.
        ///
        ///Recommended provider: Nvidia, OpenRouter (free).
        ///
        ///IMPORTANT!
        ///To select a provider and model, start translation in GPT4Free mode!.
        /// </summary>
        public static string ProviderTooltip {
            get {
                return ResourceManager.GetString("ProviderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To use GPT4Free, the following components must be installed. After installation, click &apos;Check&apos; to confirm..
        /// </summary>
        public static string RequirementsDescription {
            get {
                return ResourceManager.GetString("RequirementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After installing all components, click &apos;Continue&apos;.
        /// </summary>
        public static string RequirementsInformation {
            get {
                return ResourceManager.GetString("RequirementsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dependencies installed.
        /// </summary>
        public static string RequirementsInstalled {
            get {
                return ResourceManager.GetString("RequirementsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking dependencies for GPT4Free.
        /// </summary>
        public static string RequirementsTitle {
            get {
                return ResourceManager.GetString("RequirementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset prompt to default.
        /// </summary>
        public static string ResetPromptToDefault {
            get {
                return ResourceManager.GetString("ResetPromptToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset settings.
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource pack.
        /// </summary>
        public static string ResourcePackModeTitle {
            get {
                return ResourceManager.GetString("ResourcePackModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart the program to change the language..
        /// </summary>
        public static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run translate.
        /// </summary>
        public static string RunTranslation {
            get {
                return ResourceManager.GetString("RunTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings saved successfully!.
        /// </summary>
        public static string SavedSettingsMessage {
            get {
                return ResourceManager.GetString("SavedSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save translation.
        /// </summary>
        public static string SaveTranslation {
            get {
                return ResourceManager.GetString("SaveTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan.
        /// </summary>
        public static string SelectMissingTargetLocales {
            get {
                return ResourceManager.GetString("SelectMissingTargetLocales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a model for the chosen provider..
        /// </summary>
        public static string SelectModelForProviderMessage {
            get {
                return ResourceManager.GetString("SelectModelForProviderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a provider to load models..
        /// </summary>
        public static string SelectProviderToLoadModelsMessage {
            get {
                return ResourceManager.GetString("SelectProviderToLoadModelsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings reset to default values..
        /// </summary>
        public static string SettingsResetToDefaultsMessage {
            get {
                return ResourceManager.GetString("SettingsResetToDefaultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source language:.
        /// </summary>
        public static string SourceLanguage {
            get {
                return ResourceManager.GetString("SourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0} not found for mod {1}.
        ///Try changing the source language to another..
        /// </summary>
        public static string SourceLanguageFileMissingMessage {
            get {
                return ResourceManager.GetString("SourceLanguageFileMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cloning GPT4Free repository....
        /// </summary>
        public static string StageCloningGPT4Free {
            get {
                return ResourceManager.GetString("StageCloningGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing packages for GPT4Free....
        /// </summary>
        public static string StageInstallingPackagesGPT4Free {
            get {
                return ResourceManager.GetString("StageInstallingPackagesGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing dependencies in GPT4Free....
        /// </summary>
        public static string StageInstallingRequirementsGPT4Free {
            get {
                return ResourceManager.GetString("StageInstallingRequirementsGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading installer....
        /// </summary>
        public static string StartingInstallerDownload {
            get {
                return ResourceManager.GetString("StartingInstallerDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target language:.
        /// </summary>
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature determines how random and creative the model response is.
        ///
        ///The higher the value, the more diverse and less predictable the answers.
        ///
        ///For most translation and text processing tasks, 0.5 is recommended — it balances accuracy and variety..
        /// </summary>
        public static string TemperatureTooltip {
            get {
                return ResourceManager.GetString("TemperatureTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translated text.
        /// </summary>
        public static string TranslatedText {
            get {
                return ResourceManager.GetString("TranslatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel translate.
        /// </summary>
        public static string TranslationCancel {
            get {
                return ResourceManager.GetString("TranslationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation canceled..
        /// </summary>
        public static string TranslationCanceledMessage {
            get {
                return ResourceManager.GetString("TranslationCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation completed!.
        /// </summary>
        public static string TranslationCompletedMessage {
            get {
                return ResourceManager.GetString("TranslationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation mode.
        /// </summary>
        public static string TranslationMode {
            get {
                return ResourceManager.GetString("TranslationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation successfully saved!.
        /// </summary>
        public static string TranslationSavedMessage {
            get {
                return ResourceManager.GetString("TranslationSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation is not running..
        /// </summary>
        public static string TranslationStatusIdling {
            get {
                return ResourceManager.GetString("TranslationStatusIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translated {0} of {1} ({2:F2}%).
        /// </summary>
        public static string TranslationStatusRunning {
            get {
                return ResourceManager.GetString("TranslationStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation text.
        /// </summary>
        public static string TranslationText {
            get {
                return ResourceManager.GetString("TranslationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search in files....
        /// </summary>
        public static string TreeViewSearchPlaceholder {
            get {
                return ResourceManager.GetString("TreeViewSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
