//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftLocalizer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftLocalizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string ConfirmationNo {
            get {
                return ResourceManager.GetString("ConfirmationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string ConfirmationYes {
            get {
                return ResourceManager.GetString("ConfirmationYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search in table....
        /// </summary>
        public static string DataGridSearchPlaceholder {
            get {
                return ResourceManager.GetString("DataGridSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string DialogServiceErrorTitle {
            get {
                return ResourceManager.GetString("DialogServiceErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string DialogServiceInformationTitle {
            get {
                return ResourceManager.GetString("DialogServiceInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string DialogServiceSuccessTitle {
            get {
                return ResourceManager.GetString("DialogServiceSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directory path:.
        /// </summary>
        public static string DirectoryPath {
            get {
                return ResourceManager.GetString("DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GPT4Free is not installed. 
        ///Install now?.
        /// </summary>
        public static string GPT4FreeNotInstalledMessage {
            get {
                return ResourceManager.GetString("GPT4FreeNotInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GPT4Free is not running.
        ///Start now?.
        /// </summary>
        public static string GPT4FreeNotRunningMessage {
            get {
                return ResourceManager.GetString("GPT4FreeNotRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        public static string LoadingWindowTitle {
            get {
                return ResourceManager.GetString("LoadingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mods folder not found..
        /// </summary>
        public static string ModsFilesMissingMessage {
            get {
                return ResourceManager.GetString("ModsFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mods translation.
        /// </summary>
        public static string ModsModeTitle {
            get {
                return ResourceManager.GetString("ModsModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No checked files to save!.
        /// </summary>
        public static string NoCheckedFilesSavingMessage {
            get {
                return ResourceManager.GetString("NoCheckedFilesSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No checked files to translate!.
        /// </summary>
        public static string NoCheckedFilesTranslatingMessage {
            get {
                return ResourceManager.GetString("NoCheckedFilesTranslatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not selected.
        /// </summary>
        public static string NotSelectedModeTitle {
            get {
                return ResourceManager.GetString("NotSelectedModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open directory.
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Original text.
        /// </summary>
        public static string OriginalText {
            get {
                return ResourceManager.GetString("OriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program language:.
        /// </summary>
        public static string ProgramLanguage {
            get {
                return ResourceManager.GetString("ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FTB Quests folder not found..
        /// </summary>
        public static string QuestFilesMissingMessage {
            get {
                return ResourceManager.GetString("QuestFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FTB Quests.
        /// </summary>
        public static string QuestsModeTitle {
            get {
                return ResourceManager.GetString("QuestsModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart the program to change the language..
        /// </summary>
        public static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run translate.
        /// </summary>
        public static string RunTranslation {
            get {
                return ResourceManager.GetString("RunTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings saved successfully!.
        /// </summary>
        public static string SavedSettingsMessage {
            get {
                return ResourceManager.GetString("SavedSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save translation.
        /// </summary>
        public static string SaveTranslation {
            get {
                return ResourceManager.GetString("SaveTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source language:.
        /// </summary>
        public static string SourceLanguage {
            get {
                return ResourceManager.GetString("SourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0} not found for mod {1}.
        ///Try changing the source language to another..
        /// </summary>
        public static string SourceLanguageFileMissingMessage {
            get {
                return ResourceManager.GetString("SourceLanguageFileMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cloning GPT4Free repository....
        /// </summary>
        public static string StageCloningGPT4Free {
            get {
                return ResourceManager.GetString("StageCloningGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing dependencies in GPT4Free....
        /// </summary>
        public static string StageInstallingDependenciesGPT4Free {
            get {
                return ResourceManager.GetString("StageInstallingDependenciesGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installing packages for GPT4Free....
        /// </summary>
        public static string StageInstallingPackagesGPT4Free {
            get {
                return ResourceManager.GetString("StageInstallingPackagesGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target language:.
        /// </summary>
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translated text.
        /// </summary>
        public static string TranslatedText {
            get {
                return ResourceManager.GetString("TranslatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel translate.
        /// </summary>
        public static string TranslationCancel {
            get {
                return ResourceManager.GetString("TranslationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation canceled..
        /// </summary>
        public static string TranslationCanceledMessage {
            get {
                return ResourceManager.GetString("TranslationCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation completed!.
        /// </summary>
        public static string TranslationCompletedMessage {
            get {
                return ResourceManager.GetString("TranslationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation mode.
        /// </summary>
        public static string TranslationMode {
            get {
                return ResourceManager.GetString("TranslationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation successfully saved!.
        /// </summary>
        public static string TranslationSavedMessage {
            get {
                return ResourceManager.GetString("TranslationSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation status: translation is not running..
        /// </summary>
        public static string TranslationStatusIdling {
            get {
                return ResourceManager.GetString("TranslationStatusIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation status: translated {0} of {1} ({2:F2}%).
        /// </summary>
        public static string TranslationStatusRunning {
            get {
                return ResourceManager.GetString("TranslationStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search in files....
        /// </summary>
        public static string TreeViewSearchPlaceholder {
            get {
                return ResourceManager.GetString("TreeViewSearchPlaceholder", resourceCulture);
            }
        }
    }
}
