//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftLocalizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftLocalizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better Questing folder not found..
        /// </summary>
        public static string BetterQuestingFilesMissingMessage {
            get {
                return ResourceManager.GetString("BetterQuestingFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ConfirmationNo {
            get {
                return ResourceManager.GetString("ConfirmationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ConfirmationYes {
            get {
                return ResourceManager.GetString("ConfirmationYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in table....
        /// </summary>
        public static string DataGridSearchPlaceholder {
            get {
                return ResourceManager.GetString("DataGridSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogServiceErrorTitle {
            get {
                return ResourceManager.GetString("DialogServiceErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DialogServiceInformationTitle {
            get {
                return ResourceManager.GetString("DialogServiceInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string DialogServiceSuccessTitle {
            get {
                return ResourceManager.GetString("DialogServiceSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path:.
        /// </summary>
        public static string DirectoryPath {
            get {
                return ResourceManager.GetString("DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTB Quests folder not found..
        /// </summary>
        public static string FTBQuestsFilesMissingMessage {
            get {
                return ResourceManager.GetString("FTBQuestsFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPT4Free is not installed. 
        ///Install now?.
        /// </summary>
        public static string GPT4FreeNotInstalledMessage {
            get {
                return ResourceManager.GetString("GPT4FreeNotInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPT4Free is not running.
        ///Start now?.
        /// </summary>
        public static string GPT4FreeNotRunningMessage {
            get {
                return ResourceManager.GetString("GPT4FreeNotRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string LoadingWindowTitle {
            get {
                return ResourceManager.GetString("LoadingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods folder not found..
        /// </summary>
        public static string ModsFilesMissingMessage {
            get {
                return ResourceManager.GetString("ModsFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods translation.
        /// </summary>
        public static string ModsModeTitle {
            get {
                return ResourceManager.GetString("ModsModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No checked files to save!.
        /// </summary>
        public static string NoCheckedFilesSavingMessage {
            get {
                return ResourceManager.GetString("NoCheckedFilesSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No checked files to translate!.
        /// </summary>
        public static string NoCheckedFilesTranslatingMessage {
            get {
                return ResourceManager.GetString("NoCheckedFilesTranslatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        public static string NotSelectedModeTitle {
            get {
                return ResourceManager.GetString("NotSelectedModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory.
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original text.
        /// </summary>
        public static string OriginalText {
            get {
                return ResourceManager.GetString("OriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool for translating Minecraft mods using GPT4Free..
        /// </summary>
        public static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program language:.
        /// </summary>
        public static string ProgramLanguage {
            get {
                return ResourceManager.GetString("ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the program to change the language..
        /// </summary>
        public static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run translate.
        /// </summary>
        public static string RunTranslation {
            get {
                return ResourceManager.GetString("RunTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        public static string SavedSettingsMessage {
            get {
                return ResourceManager.GetString("SavedSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save translation.
        /// </summary>
        public static string SaveTranslation {
            get {
                return ResourceManager.GetString("SaveTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source language:.
        /// </summary>
        public static string SourceLanguage {
            get {
                return ResourceManager.GetString("SourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found for mod {1}.
        ///Try changing the source language to another..
        /// </summary>
        public static string SourceLanguageFileMissingMessage {
            get {
                return ResourceManager.GetString("SourceLanguageFileMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning GPT4Free repository....
        /// </summary>
        public static string StageCloningGPT4Free {
            get {
                return ResourceManager.GetString("StageCloningGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing dependencies in GPT4Free....
        /// </summary>
        public static string StageInstallingDependenciesGPT4Free {
            get {
                return ResourceManager.GetString("StageInstallingDependenciesGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing packages for GPT4Free....
        /// </summary>
        public static string StageInstallingPackagesGPT4Free {
            get {
                return ResourceManager.GetString("StageInstallingPackagesGPT4Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target language:.
        /// </summary>
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated text.
        /// </summary>
        public static string TranslatedText {
            get {
                return ResourceManager.GetString("TranslatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel translate.
        /// </summary>
        public static string TranslationCancel {
            get {
                return ResourceManager.GetString("TranslationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation canceled..
        /// </summary>
        public static string TranslationCanceledMessage {
            get {
                return ResourceManager.GetString("TranslationCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation completed!.
        /// </summary>
        public static string TranslationCompletedMessage {
            get {
                return ResourceManager.GetString("TranslationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation mode.
        /// </summary>
        public static string TranslationMode {
            get {
                return ResourceManager.GetString("TranslationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation successfully saved!.
        /// </summary>
        public static string TranslationSavedMessage {
            get {
                return ResourceManager.GetString("TranslationSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation status: translation is not running..
        /// </summary>
        public static string TranslationStatusIdling {
            get {
                return ResourceManager.GetString("TranslationStatusIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation status: translated {0} of {1} ({2:F2}%).
        /// </summary>
        public static string TranslationStatusRunning {
            get {
                return ResourceManager.GetString("TranslationStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in files....
        /// </summary>
        public static string TreeViewSearchPlaceholder {
            get {
                return ResourceManager.GetString("TreeViewSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
