namespace MinecraftLocalizer.ViewModels
{
    public partial class SettingsViewModel
    {
        private static LanguageOption[] GetProgramLanguages()
        {
            return
             [
                new LanguageOption { Content = "English", Tag = "en_us" },
                new LanguageOption { Content = "Русский", Tag = "ru_ru" },
                new LanguageOption { Content = "Українська", Tag = "uk_ua" },
                new LanguageOption { Content = "简体中文", Tag = "zh-Hans" },
                new LanguageOption { Content = "日本語", Tag = "ja_JP" }
             ];
        }

        private static LanguageOption[] GetLanguages()
        {
            return
            [
                new LanguageOption { Content = "[af_za] Afrikaans", Tag = "af_za" },
                new LanguageOption { Content = "[ar_sa] العربية", Tag = "ar_sa" },
                new LanguageOption { Content = "[ast_es] Asturianu", Tag = "ast_es" },
                new LanguageOption { Content = "[az_az] Azərbaycanca", Tag = "az_az" },
                new LanguageOption { Content = "[ba_ru] Башҡортса", Tag = "ba_ru" },
                new LanguageOption { Content = "[bar] Boarisch", Tag = "bar" },
                new LanguageOption { Content = "[be_by] Беларуская", Tag = "be_by" },
                new LanguageOption { Content = "[be_latn] Biełaruskaja", Tag = "be_latn" },
                new LanguageOption { Content = "[bg_bg] Български", Tag = "bg_bg" },
                new LanguageOption { Content = "[br_fr] Brezhoneg", Tag = "br_fr" },
                new LanguageOption { Content = "[brb] Braobans", Tag = "brb" },
                new LanguageOption { Content = "[bs_ba] Bosanski", Tag = "bs_ba" },
                new LanguageOption { Content = "[ca_es] Català", Tag = "ca_es" },
                new LanguageOption { Content = "[cs_cz] Čeština", Tag = "cs_cz" },
                new LanguageOption { Content = "[cy_gb] Cymraeg", Tag = "cy_gb" },
                new LanguageOption { Content = "[da_dk] Dansk", Tag = "da_dk" },
                new LanguageOption { Content = "[de_at] Deitsch", Tag = "de_at" },
                new LanguageOption { Content = "[de_ch] Schwiizerdutsch", Tag = "de_ch" },
                new LanguageOption { Content = "[de_de] Deutsch", Tag = "de_de" },
                new LanguageOption { Content = "[el_gr] Ελληνικά", Tag = "el_gr" },
                new LanguageOption { Content = "[en_au] English", Tag = "en_au" },
                new LanguageOption { Content = "[en_ca] English", Tag = "en_ca" },
                new LanguageOption { Content = "[en_gb] English", Tag = "en_gb" },
                new LanguageOption { Content = "[en_nz] English", Tag = "en_nz" },
                new LanguageOption { Content = "[en_us] English", Tag = "en_us" },
                new LanguageOption { Content = "[enp] Anglish", Tag = "enp" },
                new LanguageOption { Content = "[eo_uy] Esperanto", Tag = "eo_uy" },
                new LanguageOption { Content = "[es_ar] Español", Tag = "es_ar" },
                new LanguageOption { Content = "[es_cl] Español", Tag = "es_cl" },
                new LanguageOption { Content = "[es_ec] Español", Tag = "es_ec" },
                new LanguageOption { Content = "[es_es] Español", Tag = "es_es" },
                new LanguageOption { Content = "[es_mx] Español", Tag = "es_mx" },
                new LanguageOption { Content = "[es_uy] Español", Tag = "es_uy" },
                new LanguageOption { Content = "[es_ve] Español", Tag = "es_ve" },
                new LanguageOption { Content = "[esan] Andalûh", Tag = "esan" },
                new LanguageOption { Content = "[et_ee] Eesti", Tag = "et_ee" },
                new LanguageOption { Content = "[eu_es] Euskara", Tag = "eu_es" },
                new LanguageOption { Content = "[fa_ir] فارسی", Tag = "fa_ir" },
                new LanguageOption { Content = "[fi_fi] Suomi", Tag = "fi_fi" },
                new LanguageOption { Content = "[fil_ph] Filipino", Tag = "fil_ph" },
                new LanguageOption { Content = "[fo_fo] Føroyskt", Tag = "fo_fo" },
                new LanguageOption { Content = "[fr_ca] Français", Tag = "fr_ca" },
                new LanguageOption { Content = "[fr_fr] Français", Tag = "fr_fr" },
                new LanguageOption { Content = "[fra_de] Fränggisch", Tag = "fra_de" },
                new LanguageOption { Content = "[fur_it] Furlan", Tag = "fur_it" },
                new LanguageOption { Content = "[fy_nl] Frysk", Tag = "fy_nl" },
                new LanguageOption { Content = "[ga_ie] Gaeilge", Tag = "ga_ie" },
                new LanguageOption { Content = "[gd_gb] Gàidhlig", Tag = "gd_gb" },
                new LanguageOption { Content = "[gl_es] Galego", Tag = "gl_es" },
                new LanguageOption { Content = "[haw_us] 'Ōlelo Hawai'i", Tag = "haw_us" },
                new LanguageOption { Content = "[he_il] עברית", Tag = "he_il" },
                new LanguageOption { Content = "[hi_in] हिंदी", Tag = "hi_in" },
                new LanguageOption { Content = "[hn_no] Høgnorsk", Tag = "hn_no" },
                new LanguageOption { Content = "[hr_hr] Hrvatski", Tag = "hr_hr" },
                new LanguageOption { Content = "[hu_hu] Magyar", Tag = "hu_hu" },
                new LanguageOption { Content = "[hy_am] Հայերեն", Tag = "hy_am" },
                new LanguageOption { Content = "[id_id] Bahasa Indonesia", Tag = "id_id" },
                new LanguageOption { Content = "[ig_ng] Igbo", Tag = "ig_ng" },
                new LanguageOption { Content = "[io_en] Ido", Tag = "io_en" },
                new LanguageOption { Content = "[is_is] Íslenska", Tag = "is_is" },
                new LanguageOption { Content = "[isv] Medžuslovjansky", Tag = "isv" },
                new LanguageOption { Content = "[it_it] Italiano", Tag = "it_it" },
                new LanguageOption { Content = "[ja_jp] 日本語", Tag = "ja_jp" },
                new LanguageOption { Content = "[jbo_en] la .lojban.", Tag = "jbo_en" },
                new LanguageOption { Content = "[ka_ge] ქართული", Tag = "ka_ge" },
                new LanguageOption { Content = "[kk_kz] Қазақша", Tag = "kk_kz" },
                new LanguageOption { Content = "[kn_in] ಕನ್ನಡ", Tag = "kn_in" },
                new LanguageOption { Content = "[ko_kr] 한국어", Tag = "ko_kr" },
                new LanguageOption { Content = "[ksh] Kölsch/Ripoarisch", Tag = "ksh" },
                new LanguageOption { Content = "[kw_gb] Kernewek", Tag = "kw_gb" },
                new LanguageOption { Content = "[ky_kg] Кыргызча", Tag = "ky_kg" },
                new LanguageOption { Content = "[la_la] Latina", Tag = "la_la" },
                new LanguageOption { Content = "[lb_lu] Lëtzebuergesch", Tag = "lb_lu" },
                new LanguageOption { Content = "[li_li] Limburgs", Tag = "li_li" },
                new LanguageOption { Content = "[lmo] Lombard", Tag = "lmo" },
                new LanguageOption { Content = "[lo_la] ລາວ", Tag = "lo_la" },
                new LanguageOption { Content = "[lt_lt] Lietuvių", Tag = "lt_lt" },
                new LanguageOption { Content = "[lv_lv] Latviešu", Tag = "lv_lv" },
                new LanguageOption { Content = "[lzh] 文言", Tag = "lzh" },
                new LanguageOption { Content = "[mk_mk] Македонски", Tag = "mk_mk" },
                new LanguageOption { Content = "[mn_mn] Монгол", Tag = "mn_mn" },
                new LanguageOption { Content = "[ms_my] Bahasa Melayu", Tag = "ms_my" },
                new LanguageOption { Content = "[mt_mt] Malti", Tag = "mt_mt" },
                new LanguageOption { Content = "[nah] Mēxikatlahtōlli", Tag = "nah" },
                new LanguageOption { Content = "[nds_de] Plattdüütsh", Tag = "nds_de" },
                new LanguageOption { Content = "[nl_be] Vlaams", Tag = "nl_be" },
                new LanguageOption { Content = "[nl_nl] Nederlands", Tag = "nl_nl" },
                new LanguageOption { Content = "[nn_no] Norsk nynorsk", Tag = "nn_no" },
                new LanguageOption { Content = "[no_no] Norsk bokmål", Tag = "no_no" },
                new LanguageOption { Content = "[oc_fr] Occitan", Tag = "oc_fr" },
                new LanguageOption { Content = "[ovd] Övdalska", Tag = "ovd" },
                new LanguageOption { Content = "[pl_pl] Polski", Tag = "pl_pl" },
                new LanguageOption { Content = "[pls] Ngiiwa", Tag = "pls" },
                new LanguageOption { Content = "[pt_br] Português", Tag = "pt_br" },
                new LanguageOption { Content = "[pt_pt] Português", Tag = "pt_pt" },
                new LanguageOption { Content = "[qya_aa] Quenya", Tag = "qya_aa" },
                new LanguageOption { Content = "[ro_ro] Română", Tag = "ro_ro" },
                new LanguageOption { Content = "[rpr] Русскій дореформенный", Tag = "rpr" },
                new LanguageOption { Content = "[ru_ru] Русский", Tag = "ru_ru" },
                new LanguageOption { Content = "[ry_ua] Руснацькый", Tag = "ry_ua" },
                new LanguageOption { Content = "[sah_sah] Сахалыы", Tag = "sah_sah" },
                new LanguageOption { Content = "[se_no] Davvisámegiella", Tag = "se_no" },
                new LanguageOption { Content = "[sk_sk] Slovenčina", Tag = "sk_sk" },
                new LanguageOption { Content = "[sl_si] Slovenščina", Tag = "sl_si" },
                new LanguageOption { Content = "[so_so] Af-Soomaali", Tag = "so_so" },
                new LanguageOption { Content = "[sq_al] Shqip", Tag = "sq_al" },
                new LanguageOption { Content = "[sr_cs] Srpski", Tag = "sr_cs" },
                new LanguageOption { Content = "[sr_sp] Српски", Tag = "sr_sp" },
                new LanguageOption { Content = "[sv_se] Svenska", Tag = "sv_se" },
                new LanguageOption { Content = "[sxu] Säggs’sch", Tag = "sxu" },
                new LanguageOption { Content = "[szl] Ślōnskŏ", Tag = "szl" },
                new LanguageOption { Content = "[ta_in] தமிழ்", Tag = "ta_in" },
                new LanguageOption { Content = "[th_th] ไทย", Tag = "th_th" },
                new LanguageOption { Content = "[tl_ph] Tagalog", Tag = "tl_ph" },
                new LanguageOption { Content = "[tlh_aa] tlhIngan Hol", Tag = "tlh_aa" },
                new LanguageOption { Content = "[tok] toki pona", Tag = "tok" },
                new LanguageOption { Content = "[tr_tr] Türkçe", Tag = "tr_tr" },
                new LanguageOption { Content = "[tt_ru] Татарча", Tag = "tt_ru" },
                new LanguageOption { Content = "[tzo_mx] Bats'i k'op", Tag = "tzo_mx" },
                new LanguageOption { Content = "[uk_ua] Українська", Tag = "uk_ua" },
                new LanguageOption { Content = "[val_es] Català (Valencià)", Tag = "val_es" },
                new LanguageOption { Content = "[vec_it] Vèneto", Tag = "vec_it" },
                new LanguageOption { Content = "[vi_vn] Tiếng Việt", Tag = "vi_vn" },
                new LanguageOption { Content = "[vp_vl] Viossa", Tag = "vp_vl" },
                new LanguageOption { Content = "[yi_de] ייִדיש", Tag = "yi_de" },
                new LanguageOption { Content = "[yo_ng] Yorùbá", Tag = "yo_ng" },
                new LanguageOption { Content = "[zh_cn] 简体中文", Tag = "zh_cn" },
                new LanguageOption { Content = "[zh_hk] 繁體中文", Tag = "zh_hk" },
                new LanguageOption { Content = "[zh_tw] 繁體中文", Tag = "zh_tw" },
                new LanguageOption { Content = "[zlm_arab] بهاس ملايو", Tag = "zlm_arab" }
            ];
        }
    }
}

